### ISSUE TITLE
BUG : Impossible to convert from v.undefined_

### ISSUE THREAD

**Issue by qlaffont** [gcornut/valibot-json-schema#14]
Hello,
I'm building a plugin for fastify with your plugin and I have an error.
I share it with you :)  :

```bash
 Unsupported valibot schema: undefined
at assert (/home/quentin/Documents/dev/fastify-type-provider-valibot/node_modules/.pnpm/@gcornut+valibot-json-schema@0.0.22_@types+json-schema@7.0.15_esbuild-runner@2.2.2_esbuild@0.20.0_valibot@0.28.0/node_modules/@gcornut/valibot-json-schema/dist/index.js:48:11)
        at converter (/home/quentin/Documents/dev/fastify-type-provider-valibot/node_modules/.pnpm/@gcornut+valibot-json-schema@0.0.22_@types+json-schema@7.0.15_esbuild-runner@2.2.2_esbuild@0.20.0_valibot@0.28.0/node_modules/@gcornut/valibot-json-schema/dist/index.js:251:5)
        at toJSONSchema (/home/quentin/Documents/dev/fastify-type-provider-valibot/node_modules/.pnpm/@gcornut+valibot-json-schema@0.0.22_@types+json-schema@7.0.15_esbuild-runner@2.2.2_esbuild@0.20.0_valibot@0.28.0/node_modules/@gcornut/valibot-json-schema/dist/index.js:273:35)
        at Object.transform (/home/quentin/Documents/dev/fastify-type-provider-valibot/src/index.ts:66:53)
```

code : 
```
toJsonSchema({schema: v.undefined_('Empty response')})
```

**Comment by gcornut** [comment]
Hello, 
yes `undefined` does not exist in JSON and I think that JSON schema cannot force a JSON to be empty.
Maybe in your case you would want to convert it to the empty json schema `{}` but this is equivalent to valibot `any()` **so it's not at all equivalent**.
I could look into adding an option to control how the `undefined_()` schema is converted (something like: `toJsonSchema({ ..., undefinedStrategy: 'any' })`) but by default I think it should not be converted

**Comment by qlaffont** [comment]
Okay I understand your point, I think it will be better to add it for compatibility ^^

**Comment by gcornut** [comment]
Ok sure, if you are interested in contributing let me know. It should be pretty simple to add this option, it's similar to the existing `dateStrategy` option.
Otherwise I'll look into it when I have the time

**Comment by qlaffont** [comment]
I will try if I have the time too

**Comment by qlaffont** [comment]
PR : https://github.com/gcornut/valibot-json-schema/pull/15

**Comment by gcornut** [comment]
Merged and published in v0.0.23

**Comment by saturnonearth** [comment]
Is anyone else experiencing this issue with the recent update to Valibot? I wasn't sure if it was something in my own code or if others might have the same error again

**Comment by gcornut** [comment]
@saturnonearth 
Can you give more context ? 
`undefined` is not a JSON value so the default behavior of this lib is to throw on undefined schema. 

Are you using undefined on object values to indicate they can be omitted ? In which case optional is better suited

Are you using undefined as a null value ? In which case you can use just null or you can ask undefined to be converted to null with option `undefinedStrategy: null`

Are you using undefined because you don't really care for this value ? In which case you can use any or you can ask undefined to be converted to null with option `undefinedStrategy: any`

**Comment by saturnonearth** [comment]
> @saturnonearth Can you give more context ? `undefined` is not a JSON value so the default behavior of this lib is to throw on undefined schema.
> 
> Are you using undefined on object values to indicate they can be omitted ? In which case optional is better suited
> 
> Are you using undefined as a null value ? In which case you can use just null or you can ask undefined to be converted to null with option `undefinedStrategy: null`
> 
> Are you using undefined because you don't really care for this value ? In which case you can use any or you can ask undefined to be converted to null with option `undefinedStrategy: any`

It looks like this issue may be resolved when the `drizzle-valibot` adapter is fixed - so I will wait till then to see if this persists.
