### ISSUE TITLE
What about the opposite?

### ISSUE THREAD

**Issue by f-lawe** [gcornut/valibot-json-schema#2]
Hello!

It's not really an issue, but is there any plan about working on the opposite process (generating valibot configuration based on json schema) ?

Thanks!

**Comment by gcornut** [comment]
Hello, 
The conversion from json schema to valibot is not planned for now. I think it would not be too difficult to develop but I tend to only build the features that I know I will use.
Of course if any one wants to give it a try and open a pull request I'm open to that.

**Comment by gcornut** [comment]
Closing this issue as I'm archiving this project now that valibot has an official JSON schema converter :) 
https://valibot.dev/guides/json-schema/
