### ISSUE TITLE
Thanks for creating this library!

### ISSUE THREAD

**Issue by fabian-hiller** [gcornut/valibot-json-schema#61]
Thanks for creating this library! Feel free to contact me if you have any questions about Valibot. I am happy to help.

**Comment by gcornut** [comment]
Thank you for valibot :)
It's ok I think this library pretty much managed to reach its goal to convert the part from valibot that would make sense in JSON schema.
And I even got help for the migration to valibot 0.31 RC in #57 ! 

I'll probably change the versioning of the lib to follow the valibot version number (at least the major and minor part of the version) once 0.31 gets out of RC 👍
