### ISSUE TITLE
Supporting transform schemas

### ISSUE THREAD

**Issue by dmsynge** [gcornut/valibot-json-schema#71]
Hi there! First of all, thanks for this excellent library! 

I've got some schema that include transforms. At the moment, trying to generate a JSON Schema on a Valibot object that contains a transform results in an error: "Unsupported valibot validation `transform` for schema `object`". 

Valibot seems able to infer input and output types of transforms with no issues, so I'm guessing it wouldn't be impossible to implement JSON schema generation. 

One issue would be deciding whether the generate based on the input or output. For example, if you're generating an OpenAPI specification, it might make sense to use the transform input on requestBody, but the transform output for response content. So it would probably need a new option. 

I don't think this is super urgent (I haven't explored fully, but I reckon it shouldn't be too difficult to work around it with customSchemaConversion or customValidationConversion options. But I expect others will run into this problem, too. 

Anyway, let me know if this is something you've given any thought to -- and thanks again for the library :)

**Comment by gcornut** [comment]
Valibot schema transforms output can be inferred in the TS type system but this lib works in JS, at runtime. There is no way to access TS types data in JS directly.

There are some CLI utils that can convert TS types to JSON schema: [example here](https://github.com/fabian-hiller/valibot/issues/23#issuecomment-1759128792). But you can't convert all of valibot in TS types (array size contraint, regexp literal, etc.). It's bit more heavy, you need to parse TS from source code and resolve all types (almost a full TS compilation process).

**Comment by dmsynge** [comment]
Thanks for the reply! Sorry, I did not mean that you could or should generate the schema from the valibot inferred types. 

I only meant that the fact that valibot can infer input and output types of transformed schema (compared to Zod with ZodEffects types, etc) means that this might not be too difficult. 

To be honest, I haven't yet looked at the internals of either valibot or valibot-json-schema to get a sense of how difficult it might be to implement, but if I have time over the next couple of weeks I will do so and submit a PR.

**Comment by joshuajaco** [comment]
You could read the transformations from the pipe to support things like max length on strings.
E.g. https://valibot.dev/api/maxLength/ could be converted to https://json-schema.org/understanding-json-schema/reference/string#length

**Comment by gcornut** [comment]
Closing this issue as I'm archiving this project now that valibot has an official JSON schema converter :) 
https://valibot.dev/guides/json-schema/
